config/routes.rb
Rails.application.routes.draw do
  resources :squares
  resources :boards do
    member do
      post "claim_squares"
      post "randomize_numbers"
    end
  end
  resource :session
  resources :passwords, param: :token
  get "about", to: "pages#about"
  resources :games do
    member do
      get "edit_scores"
      patch "update_scores"
    end
  end
  resources :teams
  resource :sign_up
  namespace :settings do
    resource :password, only: [ :show, :update ]
    resource :profile, only: [ :show, :update ]

    root to: redirect("/settings/profile")
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game
  has_many :squares, dependent: :destroy
  has_many :users, through: :squares

  validates :name, presence: true
  validates :square_price, presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :create_squares

  def home_digit_for(column)
    home_team_numbers[column]
  end

  def away_digit_for(row)
    away_team_numbers[row]
  end

  def randomize_numbers!
    update!(
      home_team_numbers: (0..9).to_a.shuffle.join,
      away_team_numbers: (0..9).to_a.shuffle.join
    )
  end

  def numbers_randomized?
    !home_team_numbers.include?("?")
  end

  def winning_square(home_digit, away_digit)
    [ home_team_numbers.index(home_digit.to_s), away_team_numbers.index(away_digit.to_s) ]
  end

  def winner(home_digit, away_digit)
    column_index = home_team_numbers.index(home_digit.to_s)
    row_index = away_team_numbers.index(away_digit.to_s)
    squares.find_by(row: row_index, column: column_index)&.user&.nickname
  end

  def cost_for_user(user)
    squares.where(user: user)&.count * square_price
  end

  private

  def create_squares
    return if squares.exists?

    square_data = (0..9).flat_map do |row|
      (0..9).map { |column| { row: row, column: column, board_id: id } }
    end

    Square.insert_all(square_data)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: "Board was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_path, notice: "Board was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def claim_squares

    @board = Board.find(params[:id])
    square_ids = params[:square_ids] || []

    @board.squares.where(id: square_ids).update_all(
      user_id: Current.user.id,
      nickname: Current.user.nickname
    )

    redirect_to @board, notice: "Board is #{@board.id} square_ids = #{square_ids}"
  end

  def randomize_numbers

    @board = Board.find(params[:id])

    @board.randomize_numbers!

    redirect_to @board, notice: "Board is #{@board.id}"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.expect(board: [ :name, :square_price, :game_id ])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <div>
    <h3><%= "#{board.name} - $#{board.square_price} per square!" %></h3>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :square_price, style: "display: block" %>
    <%= form.number_field :square_price %>
  </div>
  
  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.select :game_id, Game.all.map { |game| [game.title, game.id] } %>
  </div>

  <% if false %>
  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.text_field :game_id %>
  </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/_grid.html.erb
<%= form_with(url: claim_squares_board_path(board), method: :post) do |form| %>

  <div class="wa-stack" style="align-items: center;">
    <%= image_tag board.game.home_team.logo, size: "100x100" %>
    <div class="wa-flank">
      <%= image_tag board.game.away_team.logo, size: "100x100" %>

      <div class="squares-grid-container">
      <div class="squares-grid wa-grid wa-gap-xs">
        <% (0..10).each do |col| %>
          <wa-card class="square-cell">
            <div class="wa-stack wa-align-items-center wa-gap-s">
              <%= board.home_digit_for(col-1) unless col == 0 %>
            </div>
          </wa-card>
        <% end %>
        <% (0..9).each do |row| %>
          <% (0..10).each do |column| %>
            <% if column == 0 %>
              <wa-card class="square-cell">
                <div class="wa-stack wa-align-items-center wa-gap-s">
                  <%= board.away_digit_for(row) %>
                </div> 
              </wa-card>
            <% else %>
              <% square = board.squares.find_by(row: row, column: column-1) %>
              <% if square&.nickname.present? %>
                <wa-card class="square-cell">
                  <div class="wa-stack wa-align-items-center wa-gap-s">
                    <wa-tooltip for="<%= "square_#{row}_#{column-1}" %>"><%= "#{square.nickname} aka #{square.user.first_name}" %></wa-tooltip>
                    <span class="wa-body-xs" id="<%= "square_#{row}_#{column-1}" %>"><%= "#{square.nickname[0,9]}" %><%= "..." if square.nickname.length >= 10 %></span>
                  </div>
                </wa-card>
              <% else %>
                <wa-card class="square-cell">
                  <div class="wa-stack wa-align-items-center wa-gap-s">
                    <%= check_box_tag "square_ids[]", square&.id, false, id: "square_#{square&.id}" %>
                  </div>
                </wa-card>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      </div>
    </div>
    <div class="wa-flank">
      <%# form.submit "Claim Selected Squares", class: "wa-button", variant: "brand" %>
      <wa-button variant="brand" type="submit">Claim Selected Squares</wa-button>
    </div>
  </div>
<% end %>
<%= button_to "Randomize Numbers", randomize_numbers_board_path(board) if current_user_admin? %>

app/views/boards/_winners.html.erb
<wa-drawer label="Winners" id="winners-drawer">

  <table style="max-width: 300px;">
    <caption class="wa-heading-l">Congrats!</caption>
    <thead style="font-weight: bold;">
      <td>Quarter</td>
      <td>Home Digit</td>
      <td>Away Digit</td>
      <td>Winner</td>
    </thead>
    <tbody>
      <% (1..4).each do |i| %>
        <tr>
          <td><%= i %></td>
          <td><%= board.game.winning_digit_for_quarter(i,"home") %></td>
          <td><%= board.game.winning_digit_for_quarter(i,"away") %></td>
          <td><%= board.winner(board.game.winning_digit_for_quarter(i,"home"),board.game.winning_digit_for_quarter(i,"away")) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <wa-button slot="footer" variant="brand" data-drawer="close">Close</wa-button>
</wa-drawer>

app/views/boards/_your_squares.html.erb
<wa-drawer label="Your Squares" id="your-squares-drawer">

  <table style="max-width: 300px;">
    <caption class="wa-heading-l">Good Luck!</caption>
    <thead style="font-weight: bold;">
      <td><%= board.game.home_team.full_name %></td>
      <td><%= board.game.away_team.full_name %></td>
    </thead>
    <tbody>
      <% board.squares.where(user_id: Current.user.id).each do |square| %> 
        <tr>
          <td><%= board.home_digit_for(square.column) %></td>
          <td><%= board.away_digit_for(square.row) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <span class="wa-heading-m"><%= "You owe $#{board.cost_for_user(Current.user.id)}" %></span>
  <wa-button slot="footer" variant="brand" data-drawer="close">Close</wa-button>
</wa-drawer>

app/views/boards/edit.html.erb
<% content_for :title, "Editing board" %>

<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Boards" %>

<h3>Boards</h3>

<div id="boards">
  <table>
    <caption class="wa-heading-l">Available Boards</caption>
    <thead style="font-weight: bold;">
      <td>Name</td>
      <td>Game</td>
      <td>Square Price</td>
    </thead>
    <tbody>
      <% @boards.each do |board| %>
        <%# render board %>
        <tr>
          <td><%= link_to board.name, board %></td>
          <td><%= board.game.title %></td>
          <td><%= number_to_currency(board.square_price, precision: 0) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<% content_for :title, "New board" %>

<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="wa-stack wa-align-items-center wa-gap-s">
  <%= render @board %>
  <%= render "games/scoreboard", game: @board.game %>

  <%= turbo_frame_tag "grid_#{@board.id}" do %>
    <%= render "your_squares", board: @board %>
    <%= render "grid", board: @board %>
  <% end %>

  <div class="wa-cluster wa-align-items-center wa-gap-s">
    <wa-button id="your-squares-button" variant="brand">View Your Squares</wa-button>
    <wa-button id="winners-button" variant="brand">View Winners</wa-button>
  </div>
  <%= link_to "Edit this board", edit_board_path(@board) if current_user_admin? %>
  <%= link_to "Back to Boards...", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete if current_user_admin? %>
  <%= render "winners", board: @board %>
</div>

<script>
  document.getElementById('your-squares-button').addEventListener('click', () => {
    document.getElementById('your-squares-drawer').open = true;
  });
</script>

<script>
  document.getElementById('winners-button').addEventListener('click', () => {
    document.getElementById('winners-drawer').open = true;
  });
</script>