config/routes.rb
Rails.application.routes.draw do
  resources :squares
  resources :boards do
    member do
      post "claim_squares"
      post "randomize_numbers"
    end
  end
  resource :session
  resources :passwords, param: :token
  get "about", to: "pages#about"
  resources :games do
    member do
      get "edit_scores"
      patch "update_scores"
    end
  end
  resources :teams
  resource :sign_up
  namespace :settings do
    resource :password, only: [ :show, :update ]
    resource :profile, only: [ :show, :update ]

    root to: redirect("/settings/profile")
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_footer.html.erb
<span style="font-size: 20px;">Made with <wa-icon family="notdog" type="solid" name="heart" style="color: #ff0000;"></wa-icon> in Austin, Texas</span>

app/views/layouts/_header.html.erb
<div class="wa-cluster" style="display: flex; justify-content: space-between; align-items: center; width: 100%;">
  <%= link_to "/", style: "text-decoration: none;" do %>
    <div class="wa-cluster" style="font-size: 30px;">
      <wa-icon family="sharp-duotone" type="thin" name="football" style="--primary-color: var(--wa-color-yellow-20); --secondary-color: var(--wa-color-gray-95);"></wa-icon>
      <wa-icon family="sharp-duotone" type="thin" name="basketball" style="--primary-color: var(--wa-color-gray-05); --secondary-color: var(--wa-color-red-10);"></wa-icon>
      <strong class="wa-heading-2xl" style="color: #000000;">Sportsball Squares</strong>
    </div>
  <% end %>
  <div>
    <%= link_to "Log in", new_session_path, style: "text-decoration: none;" unless authenticated? %>
    <%= link_to "Edit Profile", settings_root_path if authenticated? %>
    <%= link_to "Sign Up", sign_up_path unless authenticated? %>
    <%= link_to "Log out", session_path, style: "text-decoration: none;", data: { turbo_method: :delete } if authenticated? %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<%= link_to "Teams", teams_path, class: "wa-link-plain" if current_user_admin? %>
<%= link_to "Games", games_path, class: "wa-link-plain" if current_user_admin?  %>
<%= link_to "Boards", boards_path, class: "wa-link-plain" %>
<%= link_to "About", about_path, class: "wa-link-plain" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="wa-cloak">
  <head>
    <title><%= content_for(:title) || "Sbsquares" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Sbsquares">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Adding my Web Awesome Pro project %>
    <script src="https://kit.webawesome.com/e754ca862e634dc4.js" crossorigin="anonymous"></script>
  </head>

  <wa-page class="wa-cloak">

    <header slot="header">
      <%= render "layouts/header" %>
    </header>

    <nav slot="navigation">
      <%= render "layouts/nav" %>
    </nav>

    <body>
      <wa-card>
        <%= yield %>
      </wa-card>
    </body>

    <footer slot="footer">
      <%= render "layouts/footer" %>
    </footer>

  </wa-page>

</html>